module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@config$': '<rootDir>/src/config',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@database$': '<rootDir>/src/database',
    '^@dtos/(.*)$': '<rootDir>/src/dtos/$1',
    '^@exceptions/(.*)$': '<rootDir>/src/exceptions/$1',
    '^@interfaces/(.*)$': '<rootDir>/src/interfaces/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@thrilled/be-auth$': '<rootDir>/../../../../packages/be/auth/src/index.ts',
    '^@thrilled/databases$': '<rootDir>/../../../../packages/be/databases/src/index.ts',
    '^@thrilled/be-validation$': '<rootDir>/../../../../packages/be/validation/src/index.ts',
    '^@thrilled/be-types$': '<rootDir>/../../../../packages/be/be-types/src/index.ts',
    '^@mono/be-core$': '<rootDir>/../../../../packages/be/core/src/index.ts',
  },
  transformIgnorePatterns: [
    'node_modules/(?!@thrilled)',
  ],
  resolver: '<rootDir>/test-resolver.js',
};
